[build]
  publish = "."
  functions = "netlify/functions"
  ignore = "git log -1 --pretty=%B | grep -q '(0 new)'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
